# GuardLoop.dev Configuration Example
# Copy this file to ~/.guardloop/config.yaml and customize for your environment

version: "1.0"

# Operating mode: "standard" or "strict"
mode: "standard"

# Default agent selection: "auto" or specific agent name
# Options: auto, orchestrator, architect, coder, tester, reviewer, security, performance, ux, docs, refactor, debug, deployment, integration
default_agent: "auto"

# AI Tool configurations
tools:
  claude:
    cli_path: "claude"
    enabled: true
    timeout: 30
  gemini:
    cli_path: "gemini"
    enabled: true
    timeout: 30
  codex:
    cli_path: "codex"
    enabled: true
    timeout: 30

# Guardrail document paths
guardrails:
  base_path: "~/.guardloop/guardrails"
  files:
    - "BPSBS.md"
    - "AI_Guardrails.md"
    - "UX_UI_Guardrails.md"
  agents_path: "~/.guardloop/guardrails/agents"

# Database configuration
database:
  path: "~/.guardloop/data/guardloop.db"
  backup_enabled: true
  backup_interval_hours: 24

# Logging configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  file: "~/.guardloop/logs/guardloop.log"
  max_size_mb: 100
  backup_count: 5

# Feature flags
features:
  background_analysis: true       # Enable background analysis of AI outputs
  failure_prediction: false       # Phase 2: AI failure prediction
  prompt_optimization: false      # Phase 2: Automatic prompt optimization
  team_sync: false               # Phase 2: Team guardrail synchronization

# Team synchronization (optional)
team:
  enabled: false
  sync_repo: ""                   # Git repository URL for team guardrails
  sync_interval_hours: 1
  branch: "main"
